### ISSUE TITLE
`IP_ADDR_V6: unbound variable` on host w/o IPv6

### ISSUE THREAD

**Issue by Haarolean** [zhuwenbing/porkbun-ddns#1]
Hi! First of all, thanks for this nice tool.

I get this error on a machine without IPv6:
```
./porkbun-ddns.sh: line 193: IP_ADDR_V6: unbound variable
```

It would be nice to be able to make it work even without v6 :)

**Comment by zhuwenbing** [comment]
It has been fixed. Thank you for your valuable comments.

**Comment by Haarolean** [comment]
@zhuwenbing thank you very much!
